### ISSUE TITLE
Name does not change.

### ISSUE THREAD

**Issue by prakharpants** [prakharpants/DigitalClock#1]
It can fetch the name from the api but is not able to change the name inside the anchor tag. 
I tried changing it by .innerText but it just does not work.

**Comment by AnB1910609** [comment]
![image](https://user-images.githubusercontent.com/97835899/201891906-b161f04a-9380-4ace-ad86-232780a811f1.png)
![image](https://user-images.githubusercontent.com/97835899/201891966-61a0ee21-dd26-4ec9-882d-f08a7799c1fa.png)
@prakharpants is it ok?
I already created a pull request

**Comment by prakharpants** [comment]
Yes. Perfect. Thanks a lot for contributing I merged the request.

**Comment by AnB1910609** [comment]
Gotchu bro!
